### PR TITLE
Update various node modules

### PR DESCRIPTION
**Pull request by stephenyeargin**
Intends to clean up any lingering vulnerability reports.

### CODE REVIEW

**Comment by robbiet480** [comment]
Thanks! 🐬 🍪 💯

**Comment by robbiet480** [comment]
@stephenyeargin Looks like its still there, I believe its coming from the homeassistant module based on tracing it through package-lock.json

**Comment by stephenyeargin** [comment]
Is it `hoek`?

**Comment by robbiet480** [comment]
Yep

**Comment by robbiet480** [comment]
@stephenyeargin Just gave you write permissions on the repo, you should be able to see the security alert now [here](https://github.com/home-assistant/hubot-home-assistant/network/dependencies)

**Comment by stephenyeargin** [comment]
👍 I've run into it a bunch, should be an easy fix.

**Comment by stephenyeargin** [comment]
@robbiet480 There's an [extra setting](https://github.com/home-assistant/hubot-home-assistant/settings/alerts) I'd need for alerts, by the way (can't access it, but guessing that's the link). Whatever "team" manages the Hubot module would need to be added there.

**Comment by robbiet480** [comment]
You just needed admin on the repo, I thought I could get away with write but oh well. I trust you implicitly since you are the only one who has submitted work here for years, so don't screw it up! But if you do, not many are watching at least :)

**Comment by stephenyeargin** [comment]
At least it's now under tests!

**Comment by robbiet480** [comment]
@stephenyeargin Just a heads up, I knocked down your permissions to write during a standard organization wide permissions cleanup. If you need admin again just let me know!

**Comment by stephenyeargin** [comment]
@robbiet480 No worries. I think I should still get the Security Alerts.

**Pull request merged**
